# Generated by Django 4.2.23 on 2025-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FEATURED_STORY', 'Featured Story'), ('PRESS_RELEASE', 'Press Release')], db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, help_text="External 'Read more' URL (optional)")),
                ('image', models.ImageField(upload_to='media_center/')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Post',
                'verbose_name_plural': 'Media Posts',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['type', 'is_published', 'date'], name='media_cente_type_444db4_idx')],
            },
        ),
    ]
