# Generated by Django 4.2.23 on 2025-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('CAMPAIGN', 'Campaign Highlight')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_center/gallery/')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from public API.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['type', 'is_published'], name='media_cente_type_340a54_idx'), models.Index(fields=['sort_order'], name='media_cente_sort_or_6baaf9_idx')],
            },
        ),
    ]
