# Generated by Django 5.2.4 on 2025-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('donor', 'Donor'), ('volunteer', 'Volunteer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
