# Generated by Django 5.2.4 on 2025-08-07 10:02

import django.db.models.deletion
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='caregiver_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='caregiver_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis_info',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment_status',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='province_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver')], default='patient', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='step_completed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_prescription', models.FileField(help_text="Upload doctor's prescription", upload_to=patients.models.upload_to_prescriptions)),
                ('requested_amount_pkr', models.DecimalField(decimal_places=2, help_text='Requested amount in PKR', max_digits=10)),
                ('contribution_amount_pkr', models.DecimalField(decimal_places=2, help_text='Contribution amount in PKR', max_digits=10)),
                ('cycle_number', models.IntegerField()),
                ('description', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('supporting_documents', models.FileField(blank=True, help_text='Optional supporting documents', null=True, upload_to=patients.models.upload_to_supporting_docs)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_assistance', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sma_type', models.CharField(choices=[('type_1', 'Type 1'), ('type_2', 'Type 2'), ('type_3', 'Type 3'), ('type_4', 'Type 4')], max_length=10)),
                ('date_of_diagnosis', models.DateField()),
                ('examined_by_doctor', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('family_history', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('gene_test_report', models.FileField(help_text='Upload gene test report file', upload_to=patients.models.upload_to_gene_reports)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_confirmation', to='patients.patient')),
            ],
        ),
    ]
