# Generated by Django 5.2.4 on 2025-08-07 11:07

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_caregiver_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialassistance',
            name='contribution_amount_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contribution amount in PKR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistance',
            name='cycle_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistance',
            name='doctors_prescription',
            field=models.FileField(blank=True, help_text="Upload doctor's prescription", null=True, upload_to=patients.models.upload_to_prescriptions),
        ),
        migrations.AlterField(
            model_name='financialassistance',
            name='requested_amount_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Requested amount in PKR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalconfirmation',
            name='date_of_diagnosis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalconfirmation',
            name='examined_by_doctor',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalconfirmation',
            name='family_history',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalconfirmation',
            name='gene_test_report',
            field=models.FileField(blank=True, help_text='Upload gene test report file', null=True, upload_to=patients.models.upload_to_gene_reports),
        ),
        migrations.AlterField(
            model_name='medicalconfirmation',
            name='sma_type',
            field=models.CharField(blank=True, choices=[('type_1', 'Type 1'), ('type_2', 'Type 2'), ('type_3', 'Type 3'), ('type_4', 'Type 4')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_registration_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='province_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('caregiver', 'Caregiver')], default='patient', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='step_completed',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
